wandb:
    API_KEY: "e8cb271ec197be5b866d92ce11ae09dd17d513c3"

dataset:
    img_dir: ""
    meta_dir: /storage/lab01/ilsan_brain_infarction/metadata/20240702_전체데이터(가공).xlsx
    add_context: True
    train_size: 0.8
    val_size: 0.1
    test_size: 0.1

prompt:
    priming: "You are a neurologist and now you are analyzing sDWI b1000 images from subjects who may be diagnosed with stroke."
    quest: "Question: In the following, what will this subject be diagnosed with? 
{
  Lesion : 'Y' or 'N'
  Injury time : 'Acute' or 'Chronic' or 'Recent' or 'Old'
  Character: 'infarction' or 'hemorrhage' or 'ICH'
}"
    ans_template: "This subject will be diagnosed with"
    
model: 
    image_encoder:
        vit_model: "eva_clip_g"
        img_size: 128
        patch_size: 16
        drop_path_rate: 0
        use_grad_checkpoint: False
        freeze_vit: True
        lora_vit: False
        num_query_token: 32
    language_encoder: 
        lm_model: "Qwen/Qwen-7B-Chat"
        prompt: ""
        max_txt_len: 100
        apply_lemmatizer: False
        embed_dim: 256
        use_flash_attn: False

training_parameters:
    seed: 1234
    batch_size: 4
    accumulation_steps: 64
    num_workers: 32
    optimizer: "AdamW"
    learning_rate: 0.0001
    weight_decay: 0.01
    lr_scheduler: 

pl_trainer: 
    max_epochs: 100
    devices: 4
    accelerator: 'gpu'
    precision: 'bf16'
    num_nodes: 1
    strategy: 'DeepSpeed_Zero3_offload'
    logger: "wandb" 
    log_every_n_steps: 10
    ckpt_dir: "/storage/lab01/ilsan_brain_infarction/checkpoints"