wandb:
    API_KEY: ""

dataset:
    img_dir: ""
    meta_dir: /storage/lab01/ilsan_brain_infarction/metadata/20240819_전체데이터(가공)_1000.xlsx
    add_context: True
    train_size: 0.8
    val_size: 0.1
    test_size: 0.1
    img_size: 128
    
model: 
    architecture: "blip2_t5"
    type: "pretrain_flant5xl"
    image_encoder:
        freeze_vit: True
        lora_vit: False
    language_encoder: 
        lora_llm: False
        max_txt_len: 32


training_parameters:
    seed: 1234
    batch_size: 4
    accumulation_steps: 64
    num_workers: 64
    optimizer: "AdamW"
    learning_rate: 0.0001
    weight_decay: 0.01
    lr_scheduler: 

pl_trainer: 
    max_epochs: 100
    devices: 4
    accelerator: 'gpu'
    precision: 'bf16'
    num_nodes: 1
    strategy: 'DeepSpeed_Zero3_offload'
    logger: "wandb" 
    log_every_n_steps: 1
    ckpt_dir: "/storage/lab01/ilsan_brain_infarction/checkpoints"
    resume_training: False
